FROM golang:1.16.5-buster as builder
RUN apt-get update -qq && apt-get install -y git make
WORKDIR /go/src/github.com/moov-io/bai2
COPY . .
RUN go mod download && go mod vendor
WORKDIR /go/src/github.com/moov-io/bai2/test/fuzz-reader
RUN make install
RUN make fuzz-build
ENTRYPOINT make fuzz-run
