// Copyright 2022 The Moov Authors
// Use of this source code is governed by an Apache License
// license that can be found in the LICENSE file.

package bai3

// Uniform type codes from Appendix A. BTR3 reuses this catalog; type 89/90
// batch and invoice records from BTRS v1 are not implemented.
var typeCodeCatalog = map[string]TypeCode{
	"010": {Code: "010", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Opening Ledger"},
	"011": {Code: "011", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Opening Ledger MTD"},
	"012": {Code: "012", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Opening Ledger YTD"},
	"015": {Code: "015", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Closing Ledger"},
	"020": {Code: "020", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Closing Ledger MTD"},
	"021": {Code: "021", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Closing Ledger – Previous Month"},
	"022": {Code: "022", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Aggregate Balance Adjustments"},
	"024": {Code: "024", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Closing Ledger YTD – Previous Month"},
	"025": {Code: "025", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Closing Ledger YTD"},
	"030": {Code: "030", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Current Ledger"},
	"037": {Code: "037", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "ACH Net Position"},
	"039": {Code: "039", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Opening Available + Total Same-Day ACH DTC Deposit"},
	"040": {Code: "040", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Opening Available"},
	"041": {Code: "041", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Opening Available MTD"},
	"042": {Code: "042", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Opening Available YTD"},
	"043": {Code: "043", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Available – Previous Month"},
	"044": {Code: "044", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Disbursing Opening Available Balance"},
	"045": {Code: "045", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Closing Available"},
	"050": {Code: "050", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Closing Available MTD"},
	"051": {Code: "051", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Closing Available – Last Month"},
	"054": {Code: "054", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Closing Available YTD – Last Month"},
	"055": {Code: "055", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Closing Available YTD"},
	"056": {Code: "056", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Loan Balance"},
	"057": {Code: "057", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Total Investment Position"},
	"059": {Code: "059", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Current Available (CRS Suppressed)"},
	"060": {Code: "060", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Current Available"},
	"061": {Code: "061", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Current Available MTD"},
	"062": {Code: "062", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Current Available YTD"},
	"063": {Code: "063", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Total Float"},
	"065": {Code: "065", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Target Balance"},
	"066": {Code: "066", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Adjusted Balance"},
	"067": {Code: "067", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Adjusted Balance MTD"},
	"068": {Code: "068", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Adjusted Balance YTD"},
	"070": {Code: "070", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "0-Day Float"},
	"072": {Code: "072", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "1-Day Float"},
	"073": {Code: "073", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Float Adjustment"},
	"074": {Code: "074", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "2 or More Days Float"},
	"075": {Code: "075", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "3 or More Days Float"},
	"076": {Code: "076", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Adjustment to Balances"},
	"077": {Code: "077", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Adjustment to Balances MTD"},
	"078": {Code: "078", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average Adjustment to Balances YTD"},
	"079": {Code: "079", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "4-Day Float"},
	"080": {Code: "080", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "5-Day Float"},
	"081": {Code: "081", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "6-Day Float"},
	"082": {Code: "082", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average 1-Day Float MTD"},
	"083": {Code: "083", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average 1-Day Float YTD"},
	"084": {Code: "084", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average 2-Day Float MTD"},
	"085": {Code: "085", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Average 2-Day Float YTD"},
	"086": {Code: "086", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Transfer Calculation"},
	"100": {Code: "100", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Credits"},
	"101": {Code: "101", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Credit Amount MTD"},
	"105": {Code: "105", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Credits Not Detailed"},
	"106": {Code: "106", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Deposits Subject to Float"},
	"107": {Code: "107", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Adjustment Credits YTD"},
	"108": {Code: "108", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Credit (Any Type)"},
	"109": {Code: "109", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Current Day Total Lockbox Deposits"},
	"110": {Code: "110", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Lockbox Deposits"},
	"115": {Code: "115", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Lockbox Deposit"},
	"116": {Code: "116", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Item in Lockbox Deposit"},
	"118": {Code: "118", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Lockbox Adjustment Credit"},
	"120": {Code: "120", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "EDI* Transaction Credit"},
	"121": {Code: "121", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "EDI Transaction Credit"},
	"122": {Code: "122", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "EDIBANX Credit Received"},
	"123": {Code: "123", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "EDIBANX Credit Return"},
	"130": {Code: "130", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Concentration Credits"},
	"131": {Code: "131", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total DTC Credits"},
	"135": {Code: "135", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "DTC Concentration Credit"},
	"136": {Code: "136", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Item in DTC Deposit"},
	"140": {Code: "140", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total ACH Credits"},
	"142": {Code: "142", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ACH Credit Received"},
	"143": {Code: "143", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Item in ACH Deposit"},
	"145": {Code: "145", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ACH Concentration Credit"},
	"146": {Code: "146", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Bank Card Deposits"},
	"147": {Code: "147", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Bank Card Deposit"},
	"150": {Code: "150", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Preauthorized Payment Credits"},
	"155": {Code: "155", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Preauthorized Draft Credit"},
	"156": {Code: "156", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Item in PAC Deposit"},
	"160": {Code: "160", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total ACH Disbursing Funding Credits"},
	"162": {Code: "162", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Corporate Trade Payment Settlement"},
	"163": {Code: "163", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Corporate Trade Payment Credits"},
	"164": {Code: "164", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Corporate Trade Payment Credit"},
	"165": {Code: "165", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Preauthorized ACH Credit"},
	"166": {Code: "166", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ACH Settlement"},
	"167": {Code: "167", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "ACH Settlement Credits"},
	"168": {Code: "168", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ACH Return Item or Adjustment Settlement"},
	"169": {Code: "169", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Miscellaneous ACH Credit"},
	"170": {Code: "170", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Other Check Deposits"},
	"171": {Code: "171", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Loan Deposit"},
	"172": {Code: "172", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Deposit Correction"},
	"173": {Code: "173", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Bank-Prepared Deposit"},
	"174": {Code: "174", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Other Deposit"},
	"175": {Code: "175", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Check Deposit Package"},
	"176": {Code: "176", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Re-presented Check Deposit"},
	"178": {Code: "178", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "List Post Credits"},
	"180": {Code: "180", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Loan Proceeds"},
	"182": {Code: "182", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Bank-Prepared Deposits"},
	"184": {Code: "184", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Draft Deposit"},
	"185": {Code: "185", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Miscellaneous Deposits"},
	"186": {Code: "186", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Cash Letter Credits"},
	"187": {Code: "187", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Cash Letter Credit"},
	"188": {Code: "188", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Cash Letter Adjustments"},
	"189": {Code: "189", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Cash Letter Adjustment"},
	"190": {Code: "190", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Incoming Money Transfers"},
	"191": {Code: "191", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Incoming Internal Money Transfer"},
	"195": {Code: "195", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Incoming Money Transfer"},
	"196": {Code: "196", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Money Transfer Adjustment"},
	"198": {Code: "198", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Compensation"},
	"200": {Code: "200", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Automatic Transfer Credits"},
	"201": {Code: "201", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Automatic Transfer Credit"},
	"202": {Code: "202", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Bond Operations Credit"},
	"205": {Code: "205", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Book Transfer Credits"},
	"206": {Code: "206", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Book Transfer Credit"},
	"207": {Code: "207", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total International Money Transfer Credits"},
	"208": {Code: "208", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual International Money Transfer Credit"},
	"210": {Code: "210", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total International Credits"},
	"212": {Code: "212", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Foreign Letter of Credit"},
	"213": {Code: "213", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Letter of Credit"},
	"214": {Code: "214", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Foreign Exchange of Credit"},
	"215": {Code: "215", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Letters of Credit"},
	"216": {Code: "216", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Foreign Remittance Credit"},
	"218": {Code: "218", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Foreign Collection Credit"},
	"221": {Code: "221", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Foreign Check Purchase"},
	"222": {Code: "222", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Foreign Checks Deposited"},
	"224": {Code: "224", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Commission"},
	"226": {Code: "226", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "International Money Market Trading"},
	"227": {Code: "227", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Standing Order"},
	"229": {Code: "229", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Miscellaneous International Credit"},
	"230": {Code: "230", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Security Credits"},
	"231": {Code: "231", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Collection Credits"},
	"232": {Code: "232", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Sale of Debt Security"},
	"233": {Code: "233", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Securities Sold"},
	"234": {Code: "234", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Sale of Equity Security"},
	"235": {Code: "235", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Matured Reverse Repurchase Order"},
	"236": {Code: "236", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Maturity of Debt Security"},
	"237": {Code: "237", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Collection Credit"},
	"238": {Code: "238", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Collection of Dividends"},
	"239": {Code: "239", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Bankers’ Acceptance Credits"},
	"240": {Code: "240", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Coupon Collections – Banks"},
	"241": {Code: "241", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Bankers’ Acceptances"},
	"242": {Code: "242", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Collection of Interest Income"},
	"243": {Code: "243", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Matured Fed Funds Purchased"},
	"244": {Code: "244", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Interest/Matured Principal Payment"},
	"245": {Code: "245", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Monthly Dividends"},
	"246": {Code: "246", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Commercial Paper"},
	"247": {Code: "247", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Capital Change"},
	"248": {Code: "248", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Savings Bonds Sales Adjustment"},
	"249": {Code: "249", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Miscellaneous Security Credit"},
	"250": {Code: "250", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Checks Posted and Returned"},
	"251": {Code: "251", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Debit Reversals"},
	"252": {Code: "252", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Debit Reversal"},
	"254": {Code: "254", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Posting Error Correction Credit"},
	"255": {Code: "255", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Check Posted and Returned"},
	"256": {Code: "256", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total ACH Return Items"},
	"257": {Code: "257", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual ACH Return Item"},
	"258": {Code: "258", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ACH Reversal Credit"},
	"260": {Code: "260", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Rejected Credits"},
	"261": {Code: "261", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Rejected Credit"},
	"263": {Code: "263", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Overdraft"},
	"266": {Code: "266", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Return Item"},
	"268": {Code: "268", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Return Item Adjustment"},
	"270": {Code: "270", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total ZBA Credits"},
	"271": {Code: "271", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Net Zero-Balance Amount"},
	"274": {Code: "274", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Cumulative** ZBA or Disbursement Credits"},
	"275": {Code: "275", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ZBA Credit"},
	"276": {Code: "276", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ZBA Float Adjustment"},
	"277": {Code: "277", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ZBA Credit Transfer"},
	"278": {Code: "278", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ZBA Credit Adjustment"},
	"280": {Code: "280", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Controlled Disbursing Credits"},
	"281": {Code: "281", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Controlled Disbursing Credit"},
	"285": {Code: "285", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total DTC Disbursing Credits"},
	"286": {Code: "286", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual DTC Disbursing Credit"},
	"294": {Code: "294", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total ATM Credits"},
	"295": {Code: "295", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "ATM Credit"},
	"301": {Code: "301", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Commercial Deposit"},
	"302": {Code: "302", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Correspondent Bank Deposit"},
	"303": {Code: "303", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Wire Transfers In – FF"},
	"304": {Code: "304", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Wire Transfers In – CHF"},
	"305": {Code: "305", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Fed Funds Sold"},
	"306": {Code: "306", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Fed Funds Sold"},
	"307": {Code: "307", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Trust Credits"},
	"308": {Code: "308", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Trust Credit"},
	"309": {Code: "309", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Value - Dated Funds"},
	"310": {Code: "310", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Commercial Deposits"},
	"315": {Code: "315", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total International Credits – FF"},
	"316": {Code: "316", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total International Credits – CHF"},
	"318": {Code: "318", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Foreign Check Purchased"},
	"319": {Code: "319", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Late Deposit"},
	"320": {Code: "320", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Sold – FF"},
	"321": {Code: "321", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Sold – CHF"},
	"324": {Code: "324", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Matured – FF"},
	"325": {Code: "325", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Matured – CHF"},
	"326": {Code: "326", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Interest"},
	"327": {Code: "327", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Matured"},
	"328": {Code: "328", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Interest – FF"},
	"329": {Code: "329", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Interest – CHF"},
	"330": {Code: "330", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Escrow Credits"},
	"331": {Code: "331", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Escrow Credit"},
	"332": {Code: "332", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Miscellaneous Securities Credits – FF"},
	"336": {Code: "336", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Miscellaneous Securities Credits – CHF"},
	"338": {Code: "338", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Securities Sold"},
	"340": {Code: "340", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Broker Deposits"},
	"341": {Code: "341", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Broker Deposits – FF"},
	"342": {Code: "342", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Broker Deposit"},
	"343": {Code: "343", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Broker Deposits – CHF"},
	"344": {Code: "344", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Back Value Credit"},
	"345": {Code: "345", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Item in Brokers Deposit"},
	"346": {Code: "346", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Sweep Interest Income"},
	"347": {Code: "347", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Sweep Principal Sell"},
	"348": {Code: "348", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Futures Credit"},
	"349": {Code: "349", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Principal Payments Credit"},
	"350": {Code: "350", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Investment Sold"},
	"351": {Code: "351", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Individual Investment Sold"},
	"352": {Code: "352", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Cash Center Credits"},
	"353": {Code: "353", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Cash Center Credit"},
	"354": {Code: "354", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Interest Credit"},
	"355": {Code: "355", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Investment Interest"},
	"356": {Code: "356", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Credit Adjustment"},
	"357": {Code: "357", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Credit Adjustment"},
	"358": {Code: "358", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "YTD Adjustment Credit"},
	"359": {Code: "359", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Interest Adjustment Credit"},
	"360": {Code: "360", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Credits Less Wire Transfer and Returned Checks"},
	"361": {Code: "361", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Grand Total Credits Less Grand Total Debits"},
	"362": {Code: "362", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Correspondent Collection"},
	"363": {Code: "363", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Correspondent Collection Adjustment"},
	"364": {Code: "364", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Loan Participation"},
	"366": {Code: "366", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Currency and Coin Deposited"},
	"367": {Code: "367", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Food Stamp Letter"},
	"368": {Code: "368", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Food Stamp Adjustment"},
	"369": {Code: "369", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Clearing Settlement Credit"},
	"370": {Code: "370", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Back Value Credits"},
	"372": {Code: "372", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Back Value Adjustment"},
	"373": {Code: "373", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Customer Payroll"},
	"374": {Code: "374", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Statement Recap"},
	"376": {Code: "376", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Savings Bond Letter or Adjustment"},
	"377": {Code: "377", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Treasury Tax and Loan Credit"},
	"378": {Code: "378", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Transfer of Treasury Credit"},
	"379": {Code: "379", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Government Checks Cash Letter Credit"},
	"381": {Code: "381", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Government Check Adjustment"},
	"382": {Code: "382", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Postal Money Order Credit"},
	"383": {Code: "383", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Postal Money Order Adjustment"},
	"384": {Code: "384", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Cash Letter Auto Charge Credit"},
	"385": {Code: "385", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Universal Credits"},
	"386": {Code: "386", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Cash Letter Auto Charge Adjustment"},
	"387": {Code: "387", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Fine-Sort Cash Letter Credit"},
	"388": {Code: "388", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "FRB Fine-Sort Adjustment"},
	"389": {Code: "389", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Freight Payment Credits"},
	"390": {Code: "390", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Miscellaneous Credits"},
	"391": {Code: "391", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Universal Credit"},
	"392": {Code: "392", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Freight Payment Credit"},
	"393": {Code: "393", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Itemized Credit Over $10,000"},
	"394": {Code: "394", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Cumulative** Credits"},
	"395": {Code: "395", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Check Reversal"},
	"397": {Code: "397", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Float Adjustment"},
	"398": {Code: "398", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Miscellaneous Fee Refund"},
	"399": {Code: "399", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Miscellaneous Credit"},
	"400": {Code: "400", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Debits"},
	"401": {Code: "401", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Debit Amount MTD"},
	"403": {Code: "403", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Today’s Total Debits"},
	"405": {Code: "405", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Debit Less Wire Transfers and Charge- Backs"},
	"406": {Code: "406", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Debits not Detailed"},
	"408": {Code: "408", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Float Adjustment"},
	"409": {Code: "409", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Debit (Any Type)"},
	"410": {Code: "410", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total YTD Adjustment"},
	"412": {Code: "412", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Debits (Excluding Returned Items)"},
	"415": {Code: "415", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Lockbox Debit"},
	"416": {Code: "416", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Lockbox Debits"},
	"420": {Code: "420", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "EDI Transaction Debits"},
	"421": {Code: "421", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "EDI Transaction Debit"},
	"422": {Code: "422", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "EDIBANX Settlement Debit"},
	"423": {Code: "423", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "EDIBANX Return Item Debit"},
	"430": {Code: "430", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Payable–Through Drafts"},
	"435": {Code: "435", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Payable–Through Draft"},
	"445": {Code: "445", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ACH Concentration Debit"},
	"446": {Code: "446", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total ACH Disbursement Funding Debits"},
	"447": {Code: "447", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ACH Disbursement Funding Debit"},
	"450": {Code: "450", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total ACH Debits"},
	"451": {Code: "451", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ACH Debit Received"},
	"452": {Code: "452", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Item in ACH Disbursement or Debit"},
	"455": {Code: "455", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Preauthorized ACH Debit"},
	"462": {Code: "462", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Account Holder Initiated ACH Debit"},
	"463": {Code: "463", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Corporate Trade Payment Debits"},
	"464": {Code: "464", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Corporate Trade Payment Debit"},
	"465": {Code: "465", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Corporate Trade Payment Settlement"},
	"466": {Code: "466", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ACH Settlement"},
	"467": {Code: "467", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "ACH Settlement Debits"},
	"468": {Code: "468", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ACH Return Item or Adjustment Settlement"},
	"469": {Code: "469", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Miscellaneous ACH Debit"},
	"470": {Code: "470", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Check Paid"},
	"471": {Code: "471", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Check Paid – Cumulative MTD"},
	"472": {Code: "472", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Cumulative** Checks Paid"},
	"474": {Code: "474", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Certified Check Debit"},
	"475": {Code: "475", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Check Paid"},
	"476": {Code: "476", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Federal Reserve Bank Letter Debit"},
	"477": {Code: "477", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Bank Originated Debit"},
	"478": {Code: "478", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "List Post Debits"},
	"479": {Code: "479", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "List Post Debit"},
	"480": {Code: "480", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Loan Payments"},
	"481": {Code: "481", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual Loan Payment"},
	"482": {Code: "482", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Bank-Originated Debits"},
	"484": {Code: "484", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Draft"},
	"485": {Code: "485", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "DTC Debit"},
	"486": {Code: "486", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Cash Letter Debits"},
	"487": {Code: "487", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Cash Letter Debit"},
	"489": {Code: "489", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Cash Letter Adjustment"},
	"490": {Code: "490", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Outgoing Money Transfers"},
	"491": {Code: "491", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual Outgoing Internal Money Transfer"},
	"493": {Code: "493", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Customer Terminal Initiated Money Transfer"},
	"495": {Code: "495", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Outgoing Money Transfer"},
	"496": {Code: "496", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Money Transfer Adjustment"},
	"498": {Code: "498", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Compensation"},
	"500": {Code: "500", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Automatic Transfer Debits"},
	"501": {Code: "501", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual Automatic Transfer Debit"},
	"502": {Code: "502", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Bond Operations Debit"},
	"505": {Code: "505", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Book Transfer Debits"},
	"506": {Code: "506", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Book Transfer Debit"},
	"507": {Code: "507", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total International Money Transfer Debits"},
	"508": {Code: "508", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual International Money Transfer Debits"},
	"510": {Code: "510", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total International Debits"},
	"512": {Code: "512", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Letter of Credit Debit"},
	"513": {Code: "513", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Letter of Credit"},
	"514": {Code: "514", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Foreign Exchange Debit"},
	"515": {Code: "515", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Letters of Credit"},
	"516": {Code: "516", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Foreign Remittance Debit"},
	"518": {Code: "518", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Foreign Collection Debit"},
	"522": {Code: "522", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Foreign Checks Paid"},
	"524": {Code: "524", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Commission"},
	"526": {Code: "526", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "International Money Market Trading"},
	"527": {Code: "527", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Standing Order"},
	"529": {Code: "529", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Miscellaneous International Debit"},
	"530": {Code: "530", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Security Debits"},
	"531": {Code: "531", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Securities Purchased"},
	"532": {Code: "532", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Amount of Securities Purchased"},
	"533": {Code: "533", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Security Collection Debit"},
	"534": {Code: "534", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Miscellaneous Securities DB – FF"},
	"535": {Code: "535", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Purchase of Equity Securities"},
	"536": {Code: "536", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Miscellaneous Securities Debit – CHF"},
	"537": {Code: "537", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Collection Debit"},
	"538": {Code: "538", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Matured Repurchase Order"},
	"539": {Code: "539", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Bankers’ Acceptances Debit"},
	"540": {Code: "540", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Coupon Collection Debit"},
	"541": {Code: "541", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Bankers’ Acceptances"},
	"542": {Code: "542", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Purchase of Debt Securities"},
	"543": {Code: "543", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Domestic Collection"},
	"544": {Code: "544", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Interest/Matured Principal Payment"},
	"546": {Code: "546", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Commercial paper"},
	"547": {Code: "547", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Capital Change"},
	"548": {Code: "548", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Savings Bonds Sales Adjustment"},
	"549": {Code: "549", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Miscellaneous Security Debit"},
	"550": {Code: "550", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Deposited Items Returned"},
	"551": {Code: "551", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Credit Reversals"},
	"552": {Code: "552", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Credit Reversal"},
	"554": {Code: "554", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Posting Error Correction Debit"},
	"555": {Code: "555", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Deposited Item Returned"},
	"556": {Code: "556", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total ACH Return Items"},
	"557": {Code: "557", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual ACH Return Item"},
	"558": {Code: "558", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ACH Reversal Debit"},
	"560": {Code: "560", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Rejected Debits"},
	"561": {Code: "561", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual Rejected Debit"},
	"563": {Code: "563", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Overdraft"},
	"564": {Code: "564", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Overdraft Fee"},
	"566": {Code: "566", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Return Item"},
	"567": {Code: "567", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Return Item Fee"},
	"568": {Code: "568", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Return Item Adjustment"},
	"570": {Code: "570", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total ZBA Debits"},
	"574": {Code: "574", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Cumulative ZBA Debits"},
	"575": {Code: "575", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ZBA Debit"},
	"577": {Code: "577", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ZBA Debit Transfer"},
	"578": {Code: "578", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ZBA Debit Adjustment"},
	"580": {Code: "580", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Controlled Disbursing Debits"},
	"581": {Code: "581", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual Controlled Disbursing Debit"},
	"583": {Code: "583", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Disbursing Checks Paid – Early Amount"},
	"584": {Code: "584", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Disbursing Checks Paid – Later Amount"},
	"585": {Code: "585", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Disbursing Funding Requirement"},
	"586": {Code: "586", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "FRB Presentment Estimate (Fed Estimate)"},
	"587": {Code: "587", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Late Debits (After Notification)"},
	"588": {Code: "588", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Disbursing Checks Paid-Last Amount"},
	"590": {Code: "590", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total DTC Debits"},
	"594": {Code: "594", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total ATM Debits"},
	"595": {Code: "595", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ATM Debit"},
	"596": {Code: "596", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total APR Debits"},
	"597": {Code: "597", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "ARP Debit"},
	"601": {Code: "601", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Estimated Total Disbursement"},
	"602": {Code: "602", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Adjusted Total Disbursement"},
	"610": {Code: "610", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Funds Required"},
	"611": {Code: "611", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Wire Transfers Out- CHF"},
	"612": {Code: "612", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Wire Transfers Out – FF"},
	"613": {Code: "613", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total International Debit – CHF"},
	"614": {Code: "614", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total International Debit – FF"},
	"615": {Code: "615", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Federal Reserve Bank – Commercial Bank Debit"},
	"616": {Code: "616", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Federal Reserve Bank – Commercial Bank Debit"},
	"617": {Code: "617", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Securities Purchased – CHF"},
	"618": {Code: "618", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Securities Purchased – FF"},
	"621": {Code: "621", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Broker Debits – CHF"},
	"622": {Code: "622", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Broker Debit"},
	"623": {Code: "623", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Broker Debits – FF"},
	"625": {Code: "625", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Broker Debits"},
	"626": {Code: "626", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Fed Funds Purchased"},
	"627": {Code: "627", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Fed Funds Purchased"},
	"628": {Code: "628", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Cash Center Debits"},
	"629": {Code: "629", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Cash Center Debit"},
	"630": {Code: "630", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Debit Adjustments"},
	"631": {Code: "631", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Debit Adjustment"},
	"632": {Code: "632", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Trust Debits"},
	"633": {Code: "633", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Trust Debit"},
	"634": {Code: "634", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "YTD Adjustment Debit"},
	"640": {Code: "640", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Escrow Debits"},
	"641": {Code: "641", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual Escrow Debit"},
	"644": {Code: "644", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual Back Value Debit"},
	"646": {Code: "646", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Transfer Calculation Debit"},
	"650": {Code: "650", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Investments Purchased"},
	"651": {Code: "651", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Individual Investment purchased"},
	"654": {Code: "654", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Interest Debit"},
	"655": {Code: "655", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Investment Interest Debits"},
	"656": {Code: "656", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Sweep Principal Buy"},
	"657": {Code: "657", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Futures Debit"},
	"658": {Code: "658", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Principal Payments Debit"},
	"659": {Code: "659", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Interest Adjustment Debit"},
	"661": {Code: "661", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Account Analysis Fee"},
	"662": {Code: "662", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Correspondent Collection Debit"},
	"663": {Code: "663", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Correspondent Collection Adjustment"},
	"664": {Code: "664", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Loan Participation"},
	"665": {Code: "665", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Intercept Debits"},
	"666": {Code: "666", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Currency and Coin Shipped"},
	"667": {Code: "667", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Food Stamp Letter"},
	"668": {Code: "668", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Food Stamp Adjustment"},
	"669": {Code: "669", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Clearing Settlement Debit"},
	"670": {Code: "670", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Back Value Debits"},
	"672": {Code: "672", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Back Value Adjustment"},
	"673": {Code: "673", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Customer Payroll"},
	"674": {Code: "674", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Statement Recap"},
	"676": {Code: "676", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Savings Bond Letter or Adjustment"},
	"677": {Code: "677", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Treasury Tax and Loan Debit"},
	"678": {Code: "678", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Transfer of Treasury Debit"},
	"679": {Code: "679", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Government Checks Cash Letter Debit"},
	"681": {Code: "681", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Government Check Adjustment"},
	"682": {Code: "682", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Postal Money Order Debit"},
	"683": {Code: "683", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Postal Money Order Adjustment"},
	"684": {Code: "684", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Cash Letter Auto Charge Debit"},
	"685": {Code: "685", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Universal Debits"},
	"686": {Code: "686", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Cash Letter Auto Charge Adjustment"},
	"687": {Code: "687", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Fine-Sort Cash Letter Debit"},
	"688": {Code: "688", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "FRB Fine-Sort Adjustment"},
	"689": {Code: "689", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "FRB Freight Payment Debits"},
	"690": {Code: "690", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Total Miscellaneous Debits"},
	"691": {Code: "691", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Universal Debit"},
	"692": {Code: "692", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Freight Payment Debit"},
	"693": {Code: "693", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Itemized Debit Over $10,000"},
	"694": {Code: "694", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Deposit Reversal"},
	"695": {Code: "695", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Deposit Correction Debit"},
	"696": {Code: "696", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Regular Collection Debit"},
	"697": {Code: "697", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Cumulative** Debits"},
	"698": {Code: "698", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Miscellaneous Fees"},
	"699": {Code: "699", Transaction: TransactionDB, Level: TypeLevelDetail, Description: "Miscellaneous Debit"},
	"701": {Code: "701", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Principal Loan Balance"},
	"703": {Code: "703", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Available Commitment Amount"},
	"705": {Code: "705", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Payment Amount Due"},
	"707": {Code: "707", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Principal Amount Past Due"},
	"709": {Code: "709", Transaction: TransactionNA, Level: TypeLevelStatus, Description: "Interest Amount Past Due"},
	"720": {Code: "720", Transaction: TransactionCR, Level: TypeLevelSummary, Description: "Total Loan Payment"},
	"721": {Code: "721", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Amount Applied to Interest"},
	"722": {Code: "722", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Amount Applied to Principal"},
	"723": {Code: "723", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Amount Applied to Escrow"},
	"724": {Code: "724", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Amount Applied to Late Charges"},
	"725": {Code: "725", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Amount Applied to Buydown"},
	"726": {Code: "726", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Amount Applied to Misc. Fees"},
	"727": {Code: "727", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Amount Applied to Deferred Interest Detail"},
	"728": {Code: "728", Transaction: TransactionCR, Level: TypeLevelDetail, Description: "Amount Applied to Service Charge"},
	"760": {Code: "760", Transaction: TransactionDB, Level: TypeLevelSummary, Description: "Loan Disbursement"},
	"890": {Code: "890", Transaction: TransactionNA, Level: TypeLevelDetail, Description: "Contains Non-monetary Information"},
}
