name: Go Fuzz Testing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  fuzz-writer:
    name: Fuzz Writer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 30

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Fuzz Valid Files
      run: |
        go test ./test/fuzz/... -fuzz FuzzReaderWriter_ValidFiles -fuzztime 10m

    - name: Fuzz Error Files
      run: |
        go test ./test/fuzz/... -fuzz FuzzReaderWriter_ErrorFiles -fuzztime 10m

    - name: Report Failures
      if: ${{ failure() }}
      run: |
        find ./test/fuzz/testdata/fuzz/ -type f | xargs -n1 tail -n +1 -v
